[project]
name = "quadratic"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.quadratic]
path = "contracts/quadratic.clar"
depends_on = []

[contracts.miamicoin-token]
path = "contracts/external/miamicoin-token.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"
depends_on = []
